#ifndef SHARED_DEFINITIONS_H
#define SHARED_DEFINITIONS_H

// Light culling
#define TILE_SIZE 16
#define MAX_LIGHTS_PER_TILE 1024

// Meshlets
#define MESHLET_TRIANGLE_COUNT 128
#define MESHLET_INDEX_COUNT (3 * MESHLET_TRIANGLE_COUNT)

// SSAO
#define SSAO_KERNEL_SIZE 64

// General
#define OPT_COMP_TG_SIZE 128 // Must be divisible by 32
#define OPT_TILE_SIZE 32u

#endif // SHARED_DEFINITIONS_H

